version: "3.8"
services:
  # PostgreSQL Database (Cơ sở dữ liệu cho Kong)
  kong-database:
    image: postgres:13
    container_name: kong-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kong-net
  # Kong API Gateway
  kong:
    image: kong:latest
    container_name: kong
    restart: unless-stopped
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 7000:8000 # API Gateway HTTP
      - 7443:8443 # API Gateway HTTPS
      - 7001:8001 # Admin API HTTP
      - 7444:8444 # Admin API HTTPS
    command: |
      sh -c "kong migrations bootstrap && kong start"
    networks:
      - kong-net
  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: unless-stopped
    depends_on:
      - kong
    environment:
      - NODE_ENV=production
      - TOKEN_SECRET=supersecret
      - KONGA_BACKEND_URL=http://kong:8001
    ports:
      - 7337:1337
    networks:
      - kong-net

volumes:
  kong-data: null
networks:
  kong-net:
    driver: bridge